name       : haskell-ed25519
version    : 0.0.5.0
release    : 7
source     :
    # Revision 7
    - https://hackage.haskell.org/package/ed25519-0.0.5.0/ed25519-0.0.5.0.tar.gz : d8a5958ebfa9309790efade64275dc5c441b568645c45ceed1b0c6ff36d6156d
license    : MIT
component  : programming.haskell
summary    : This package provides a simple, fast, self-contained copy of the Ed25519 public-key signature system with a clean interface.
description: |
    This package provides a simple, fast, self-contained copy of the Ed25519 public-key signature system with a clean interface.
builddeps  :
    - ghc-devel
setup      : |
    cp $pkgfiles/7.cabal ed25519.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
